# Generated by Django 5.0.4 on 2024-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
